### ISSUE TITLE
The TTS progress seems not to be working

### ISSUE THREAD

**Issue by trongthaonh** [NIKDISSV-Forever/FastDub#8]
I tried the following command as instructed:
`sudo python3 -m fastdub -yt -i https://youtu.be/DD5UKQggXTc -v "vietnam" -l vi`

The TTS progress seems not to be working, and I have been waiting for a long time with no change in the percentage. After that, when I pressed Ctrl+C, a KeyboardInterrupt error appeared as shown in the image.

<img width="1492" alt="Screen Shot 2023-10-05 at 12 36 31" src="https://github.com/NIKDISSV-Forever/FastDub/assets/4439065/9d8de3ce-d8e1-46ab-b138-13761f608e33">

How to solve this problem? Thanks in advance!

**Comment by NIKDISSV-Forever** [comment]
When you specify a link to YouTube, the video will start downloading from it, a separate progress bar should appear, if not, then the video has probably already been downloaded earlier.

In any case, then the progress of TTS will go, judging by the picture, the progress has reached 11%, if you didn't see how it moved, _probably the problem is only in the print and the console buffer_.

If the problem is that the ```KeyboardInterrupt``` has risen, then this is how it should be when you press <kbd>Ctrl + C</kbd>, the program immediately ends with an exception, you probably expected to be able to see the unfinished video, unfortunately not, now the program collects the result in the video only at the very end.
